exclude = [
  "*.ipynb",
]

# Matches the Python version used across CI jobs.
target-version = "py312"

line-length = 120
indent-width = 2

[lint]
select = ["E", "F", "B", "Q"]
ignore = []

[format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"
