name: Core Tests
  
on:
  push:
    branches: [ '**' ]

jobs:  
  test-ubuntu-gcc14:  
    runs-on: ubuntu-24.04 
    strategy:  
      matrix:  
        python-version: ["3.8"]  

    steps:  
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}  
        uses: actions/setup-python@v5 
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Python Dependencies
        run: |  
          python3 -m pip install --upgrade pip  
          if [ -f Requirements.txt ]; then python3 -m pip install -r Requirements.txt; fi  

      - name: Install g++14
        run: |
          sudo add-apt-repository universe
          sudo apt update
          sudo apt install -y g++-14 gcc-14

      - name: Install CMake
        run: sudo apt install cmake

      - name: Build and Test
        env:
          CXX: g++-14
          CC:  gcc-14
        run: |
          chmod +x automation.py
          ./automation.py --setup --clean --cmake --build --test -v 1


  test-ubuntu-clang:  
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version: ["3.12"]  

    steps:  
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}  
        uses: actions/setup-python@v5 
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Python Dependencies
        run: |  
          python3 -m pip install --upgrade pip  
          if [ -f Requirements.txt ]; then python3 -m pip install -r Requirements.txt; fi  

      - name: Install LLVM and clang++
        run: |
          sudo add-apt-repository universe
          sudo apt update
          sudo apt install -y llvm-18 clang-18

      - name: Install CMake
        run: sudo apt install cmake

      - name: Build and Test
        env:
          CXX: clang++-18
          CC:  clang-18
        run: |
          chmod +x automation.py
          ./automation.py --setup --clean --cmake --build --test -v 1


  test-macos-apple-clang:  
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: ["3.12"]  

    steps:
    - uses: actions/checkout@v4

    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    
    - name: Set up Python ${{ matrix.python-version }}  
      uses: actions/setup-python@v5 
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install Python Dependencies
      run: |  
        python3 -m pip install --upgrade pip  
        if [ -f Requirements.txt ]; then python3 -m pip install -r Requirements.txt; fi  

    - name: Build and Test
      env:
        CXX: clang++
        CC:  clang
      run: |
        chmod +x automation.py
        ./automation.py --setup --clean --cmake --build --test -v 1


  test-windows-clang:  
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.12"]  
  
    steps:  
      - uses: actions/checkout@v4

      - name: Set up Visual Studio
        uses: microsoft/setup-msbuild@v2
        with:
          vs-version: latest

      - name: Set up Python ${{ matrix.python-version }}  
        uses: actions/setup-python@v5 
        with:
          python-version: ${{ matrix.python-version }}
  
      - name: Install Dependencies
        run: |  
          python -m pip install --upgrade pip  
          if (Test-Path "Requirements.txt") { python -m pip install -r "Requirements.txt" }

          choco install -y make llvm

      - name: Build and Test
        env:
          CXX: clang++
          CC:  clang
        run: |
          chcp.com 65001
          $env:PYTHONIOENCODING = "utf-8"
          python3 ./automation.py --setup --clean --cmake --build --test -v 1
