name: Build and Test Celestial Calendar

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [ "linux/amd64", "linux/arm64" ]

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          export image_tag=$(echo celestial-calendar-${{ matrix.platform }} | tr '/' '-')
          sudo docker buildx create --use
          sudo docker buildx build --platform ${{ matrix.platform }} -t $image_tag --load .

      - name: Run Docker container
        run: |
          export image_tag=$(echo celestial-calendar-${{ matrix.platform }} | tr '/' '-')
          export output_dir=$(echo $(pwd)/output-${{ matrix.platform }} | tr '/' '-')
          mkdir -p $output_dir # Ensure the output directory exists
          sudo docker run --rm -v $output_dir:/output $image_tag
          sudo docker run --rm -v $output_dir:/output $image_tag /bin/bash -c "tree /app"
          sudo docker run --rm -v $output_dir:/output $image_tag /bin/bash -c "tree /app/build"
          sudo docker run --rm -v $output_dir:/output $image_tag /bin/bash -c "cp -r /app/build/shared_lib /output"
      
      - name: Check shared lib existence
        run: |
          export platform_arch=$(echo ${{ matrix.platform }} | tr '/' '-')
          export output_dir=$(echo $(pwd)/output-${{ matrix.platform }} | tr '/' '-')
          shared_libs=($(find $output_dir/shared_lib -type f -name "*.so" -o -name "*.dylib" -o -name "*.dll"))
          if [ ${#shared_libs[@]} -eq 0 ]; then
            echo "No shared libraries found."
            exit 1
          fi
          count=1
          for lib in "${shared_libs[@]}"; do
            extension="${lib##*.}"
            if [ $count -eq 1 ]; then
              new_name="$output_dir/shared_lib/libcelestial_calendar_${platform_arch}.${extension}"
            else
              new_name="$output_dir/shared_lib/libcelestial_calendar${count}_${platform_arch}.${extension}"
            fi
            echo "Renaming $lib to $new_name"
            mv "$lib" "$new_name"
            ((count++))
          done

      - name: Upload shared libraries
        uses: actions/upload-artifact@v3
        with:
          name: celestial-calendar-$(echo ${{ matrix.platform }} | tr '/' '-')
          path: $(echo ./output-${{ matrix.platform }} | tr '/' '-')/shared_lib/*
          if-no-files-found: error
