name: Build and Test on macOS (macOS latest / apple-clang)

on:
  workflow_dispatch: {}  # Allows manual triggering of the workflow
  # pull_request:
  #   branches: [ main ]  # Also triggers on pull requests to the main branch

jobs:
  build-shared-lib-macos:
    runs-on: macos-latest
    strategy:  
      matrix:  
        python-version: ["3.12"]  

    steps:
    - uses: actions/checkout@v4

    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    
    - name: Set up python ${{ matrix.python-version }}  
      uses: actions/setup-python@v5 
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install Python dependencies
      run: |  
        python3 -m pip install --upgrade pip  
        if [ -f Requirements.txt ]; then python3 -m pip install -r Requirements.txt; fi

    - name: Build and Test
      env:
        CXX: clang++
        CC:  clang
      run: |
        chmod +x automation.py
        ./automation.py --setup --clean --cmake --build --test -v 1

    - name: Ensure shared lib exists
      id: shared_lib
      run: |
        # Should be in ./build/shared_lib/*.dylib
        ls ./build/shared_lib

        if [ ! -f ./build/shared_lib/*.dylib ]; then
          echo "No shared lib found"
          exit 1
        fi

        # Rename the lib to lib_celecalendar_macos_arm64.dylib
        mv ./build/shared_lib/*.dylib ./build/shared_lib/lib_celecalendar_macos_arm64.dylib

        # If exists, save the path to GITHUB_OUTPUT
        echo "lib_name=lib_celecalendar_macos_arm64.dylib" >> $GITHUB_OUTPUT
        echo "lib_path=$(pwd)/build/shared_lib/lib_celecalendar_macos_arm64.dylib" >> $GITHUB_OUTPUT

        # Print to stdout
        echo "lib_name=${lib_name}"
        echo "lib_path=${lib_path}"

    - name: GitHub Artifact
      uses: actions/upload-artifact@v4
      with:
        # Upload the renamed shared library as an artifact
        name: ${{ steps.shared_lib.outputs.lib_name }}
        path: ${{ steps.shared_lib.outputs.lib_path }}
        retention-days: 30
        if-no-files-found: error
