name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Read Release Notes
        id: read_release_notes
        run: |
          RELEASE_NOTES=$(cat docs/RELEASE_NOTES.md)
          echo "release_notes=$RELEASE_NOTES" >> $GITHUB_OUTPUT

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: ${{ steps.read_release_notes.outputs.release_notes }}

      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: latest_build
          path: latest_build/

      - name: Upload Release Artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          UPLOAD_URL="${{ steps.create_release.outputs.upload_url }}"
          for file in latest_build/*; do
            if [ -f "$file" ]; then
              filename=$(basename "$file")
              curl -s -H "Authorization: token $GITHUB_TOKEN" \
                  -H "Content-Type: $(file -b --mime-type "$file")" \
                  --data-binary @"$file" \
                  "$UPLOAD_URL?name=$filename"
            fi
          done
