name: Create Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  create_release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Sanity Check on Version
        run: |
          github_ref=${{ github.ref }}
          version_nums=${github_ref##refs/tags/v}

          chmod +x project.py
          expected_version_nums=$(./project.py --version)
          expected_version_nums=$(echo "$expected_version_nums" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')

          if [ "$version_nums" != "$expected_version_nums" ]; then
            echo "Expected version number: $expected_version_nums"
            echo "Actual version number: $version_nums"
            exit 1
          fi

      - name: Download Artifacts
        run: |
          export GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}

          chmod +x toolbox/artifact_downloader.py
          ./toolbox/artifact_downloader.py --save-to ./release_assets

      - name: Copy CHANGELOG.md
        run: cp docs/CHANGELOG.md ./release_assets

      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "release_assets/*"
          bodyFile: "docs/RELEASE_NOTES.md"

