name: Workflow - Run Tests
  
on:
  push:
    branches: [ '**' ]
  pull_request:
      branches: [ main ]

jobs:  
  build:  
    runs-on: ubuntu-24.04 
    strategy:  
      matrix:  
        python-version: ["3.12"]  
  
    steps:  
      - uses: actions/checkout@v4
      - name: Set up python ${{ matrix.python-version }}  
        uses: actions/setup-python@v5 
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Python dependencies
        run: |  
          python -m pip install --upgrade pip  
          if [ -f Requirements.txt ]; then pip install -r Requirements.txt; fi  
      - name: Install g++14
        run: |
          sudo add-apt-repository universe
          sudo apt update
          sudo apt install -y g++-14 gcc-14
      - name: Install CMake
        run: sudo apt install cmake
      - name: Build and Test
        env:
          CXX: g++-14
          CC:  gcc-14
        run: |
          chmod +x build.py
          ./build.py -cmk -b -t -v 1
